apiVersion: v1
kind: Secret
metadata:
  name: backend-config
type: Opaque
data:
  BETTER_AUTH_SECRET: c3VwZXJzZWNyZXRrZXl0aGF0aXNhdGxlYXN0MzJjaGFyYWN0ZXJz  # base64 encoded from .env
  DATABASE_URL: cG9zdGdyZXNxbDovL25lb25kYl9vd25lcjpu cGdfVGt0QzlGSm1QaWc1QGVwLWF1dHVtbi1yZWNpcGUtYWRlNWhkaDQtcG9vbGVyLmMtMi51cy1lYXN0LTEuYXdzLm5lb24udGVjaC9uZW9uZGI/c3NsbW9kZT1yZXF1aXJlJmNoYW5uZWxfYmluZGluZz1yZXF1aXJl  # base64 encoded from .env